export const INCREMENT = "INCREMENT_COUNTER"
export const DECREMENT = "DECREMENT_COUNTER"

export const GET_MEDICINE = "GET_MEDICINE"

export const LOADING_MEDICINES = "LOADING_MEDICINES"
export const ERROR_MEDICINES = "ERROR_MEDICINES"