export const INCREMENT = "INCREMENT_COUNTER"
export const DECREMENT = "DECREMENT_COUNTER"

export const GET_MEDICINE = "GET_MEDICINE"

export const LOADING_MEDICINES = "LOADING_MEDICINES"
export const ERROR_MEDICINES = "ERROR_MEDICINES"
export const POST_MEDICINES = "POST_MEDICINES"
export const DELETE_MEDICINES = "DELETE_MEDICINES"
export const UPDATE_MEDICINES = "UPDATE_MEDICINES"

export const GET_DOCTOR = "GET_DOCTOR"